### ISSUE TITLE
Users Key Error

### ISSUE THREAD

**Issue by timfro** [bcanfield/southpaw#51]
Traceback (most recent call last):
  File "c:\Users\timf0\Python Projects\fanduelauto.py", line 13, in <module>
    fd = southpaw.Fanduel(fd_email, fd_pw, fd_basic, fd_session)
  File "C:\Users\timf0\Python\lib\site-packages\southpaw\fanduel.py", line 275, in __init__
    self.__authenticate()
  File "C:\Users\timf0\Python\lib\site-packages\southpaw\fanduel.py", line 444, in __authenticate
    if current_response_json and len(current_response_json['users']) > 0:
KeyError: 'users'

Looks like the headers doesn't initialize a "users" key but is referenced later. How would you go about this if it still is working?

**Comment by empire-sports** [comment]
it looks like the x-auth-token rotates.  to fix this you have to retrieve it after successfully logging into their platform.  will change.
